### ISSUE TITLE
Practica 7: Integración de funcionalidades de RA en una App para subir a un hosting

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-gps-equipo-jaciel#2]
[integración de  funcionalidades de RA en una App para subir a un hosting.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-equipo-jaciel/files/8604240/integracion.de.funcionalidades.de.RA.en.una.App.para.subir.a.un.hosting.pdf)

**Comment by Nancy2050** [comment]
Calificación 20/20 (100%)

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado....
